# Generated by Django 4.1.3 on 2023-02-12 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_instructions',
            field=ckeditor.fields.RichTextField(verbose_name='cooking instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_instructions_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='cooking instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_instructions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='cooking instructions'),
        ),
    ]
