# Generated by Django 4.1.3 on 2023-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_recipe_text_alter_recipe_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='category name'),
        ),
    ]
